### ISSUE TITLE
Feature request: rate-limited updates

### ISSUE THREAD

**Issue by twpayne** [toolctl/toolctl#85]
I would like to use `toolctl` to replace [my personal hacky install scripts](https://github.com/twpayne/dotfiles/blob/6f681f8a2f79368e0b439f077669bc75e3b3b5ff/home/.chezmoiscripts/run_once_before_20-install-gh-linux.sh.tmpl), which require manual checks for new versions and then manual edits to the scripts.

If I understand correctly, running `toolctl upgrade` checks for and downloads new versions of all installed tools. This is a potentially slow operation, as `tooclctl` must contact several servers to determine if new version is available.

I would like to use `toolctl` in a [`run_` script in chezmoi](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/), but such scripts are run every time I run chezmoi, and so need to be fast. I can't use chezmoi's `run_once_` or `run_onchange_` scripts as these lack the machinery to determine whether `toolctl upgrade` should be run or not.

Would you consider adding a mechanism to `toolctl upgrade` to only check for upgrades if a check hasn't been run recently? Something like...

```console
$ toolctl upgrade --period=24h
```

...would only run the check for new versions if no check has been run in the previous 24 hours. Of course, this means that `toolctl` will need to maintain state about when the last check was run, maybe in `~/.cache/toolctl/last-upgrade.json` or similar.

I would happily contribute a PR to implement this functionality.

An alternative would be to use a generic rate limiting wrapper script to invoke `toolctl upgrade` itself, but that would be one more tool to maintain.

**Comment by patrickhoefler** [comment]
Hey Tom,

thanks so much for your suggestion!

Let me state for the record that `chezmoi` is awesome 😀

I am totally on board with this addition! I'll dive deeper into your PR now, and I'm sure I'll have some comments, but after a quick skim it already looks really solid — more details in the PR 🙂

**Comment by twpayne** [comment]
Closing as I'm no longer using toolctl as it seems it requires maintainer involvement to add new tools. Others can re-open if needed.
